### ISSUE TITLE
关于anaconda镜像使用的疑问

### ISSUE THREAD

**Issue by shengqiangzhang** [chn-lee-yumi/mirrors-gdut#1]
@chn-lee-yumi 

首先感谢这个开源项目，让广工学子能够在校内享用高速的下载速度。

[https://mirrors.gdut.edu.cn/anaconda.html](https://mirrors.gdut.edu.cn/anaconda.html)进行了以下说明：
> 由于Anaconda镜像高达3TB+，故我们不进行全量镜像，而是进行缓存。回源站点为清华开源软件镜像站。所有数据被请求过一次后即会缓存到服务器硬盘，缓存30天

我的问题是：
1. 请问这个项目是否为学校官方项目？
2. 对于某些冷门包，使用回源的方式是否比直接使用清华源更加不方便？

**Comment by chn-lee-yumi** [comment]
1. 已提交资料给网络中心的领导，暂未答复。临近考试，也没有时间去找领导。目前在小范围测试，有望下学期上线。
2. 就镜像站使用方式来说，两者是一样的。如果这里说的“不方便”是指下载速度的话，对于一个没有被缓存的文件，首次请求确实会比直接访问清华源要慢一些。
